@url = http://localhost:3000/api
GET {{url}}/usuarios

###
GET {{url}}/preguntas

###
POST {{url}}/auth/login
Content-Type: application/json

{
    "email": "deivit@deivit.es",
    "password":"123"

}

###
POST {{url}}/auth/registro
Content-Type: application/json

{
    "username": "deivit",
    "email": "deivit@deivit.es",
    "password":"123"
}

###
GET {{url}}/brecha

###
POST {{url}}/brecha
Content-Type: application/json

{
    "username": "bcalderbank2",
    "fecha": "7/14/2020",
    "brecha": "nivel alto"
}
